# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d4d879a730ac1ddf18dd5289d19a18426df2eaf977e0c53a15649a1046d4c49fb39939ad5a39b6efa5cefb80e521848edf197ad167b47dbddfee1f6b03d451d

test:
  secret_key_base: 9a5a9ef8f674d757157bf2c2eeae345e4e8024c953c434ba2739ea7f42d11ffa972325816a1d74cfd292b0d8ae0c29aa2657cd041458b6447b57a8488a6fb0e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
